### ISSUE TITLE
Extend library with API communications

### ISSUE THREAD

**Issue by dami-gg** [zalando-incubator/solution-center-communicator#23]
I've always thought this library could be extended to include all the necessary methods and API endpoints information we have in the Solution Center repo in the backend-config service and app files, so we centralize everything related to communications in here

What do you guys think? @zalando-incubator/norris

**Comment by gregdeane** [comment]
@dami-gg I like the idea a lot. Definitely should move this direction. I would like to keep separation of Angular-specific code and our code at the forefront of our minds. Note how `environments.provider.js` has no Angular code save for the `$get`. If the communicator wasn't a provider, we could have complete separation of Angular and our code.

Let's shoot for this separation with the API addition. This will allow the communicator to be used in as many situations as possible.

**Comment by dami-gg** [comment]
Fine for me ;)

**Comment by dami-gg** [comment]
This may be interesting for that purpose:

http://www.js-data.io/docs/home
