### ISSUE TITLE
NPS / Update communicator with endpoint

### ISSUE THREAD

**Issue by gregdeane** [zalando-incubator/solution-center-communicator#27]
Need to add the NPS endpoint. See [solution-center-feedback](https://github.com/zalando-incubator/solution-center-feedback/issues?q=is%3Aopen+is%3Aissue+milestone%3A%22Sprint+CW+33+2016%22) for more info.

**Comment by dami-gg** [comment]
Can be found here: https://ms-development.norris.zalan.do/docs/swagger-ui/index.html
